### ISSUE TITLE
Add a Gym webiste

### ISSUE THREAD

**Issue by ravish036** [priyanshi1282/LGMVIP-WebDevelopment#1]
This is an fully responsive website which can be used as landing page for an fitness chain .
Tech Stack used : HTML5, CSS, JS .

![Capture](https://user-images.githubusercontent.com/84343005/183050193-b9b3705b-1942-48a6-aaa2-dc8583c91cde.PNG)
![Capture1](https://user-images.githubusercontent.com/84343005/183050301-03d59171-68c2-4955-a9fd-836acb5c2025.PNG)
![Capture3](https://user-images.githubusercontent.com/84343005/183050319-0588fea1-d743-420d-8820-0d058db62d31.PNG)
![Capture4](https://user-images.githubusercontent.com/84343005/183050179-861f21c2-913e-435c-8100-0ee8d5f6a34d.PNG)

**Comment by priyanshi1282** [comment]
nice work @ravish036

**Comment by adilwahla** [comment]
@ravish036 @priyanshi1282 Hey shout out nice job :)
